Vagrant.configure("2") do |config|
  config.vm.box = "kalilinux/rolling"
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.host_vars = {
      "default" => {"ansible_python_interpreter" => "/usr/bin/python3"}
    }
  end
end
